#include <turbo_mesh.h>
#include <p2p.h>
#include <turbo_thread.h>
#include <tlog.h>
#include "mesh_config.h"
#include "mesh_runtime_health.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
#include <signal.h>
#include <stdint.h>
#include <time.h>

#define MESH_SNAPSHOT_VERSION 1

#ifdef _WIN32
#include <windows.h>
#else
#include <unistd.h>
#endif

#define MESHCTL_MAX_COMMAND 256
#define MESHCTL_COMMAND_QUEUE_SIZE 16
typedef mesh_node_config_t meshctl_config_t;
#define meshctl_config_init mesh_node_config_init
#define meshctl_config_load mesh_node_config_load
#define meshctl_config_validate mesh_node_config_validate
#define meshctl_print_config mesh_node_config_print

typedef struct {
    turbo_mutex_t mutex;
    char commands[MESHCTL_COMMAND_QUEUE_SIZE][MESHCTL_MAX_COMMAND];
    int head;
    int tail;
    int count;
    int stop;
} meshctl_command_queue_t;

static volatile int g_running = 1;
static mesh_network_t *g_mesh = NULL;
static meshctl_config_t g_config;
static meshctl_command_queue_t g_command_queue;
static unsigned int g_ping_seq = 0;
static unsigned int g_last_ping_seq = 0;
static uint64_t g_last_ping_sent_ms = 0;
static char g_last_ping_target[16];

static void meshctl_bytes_to_hex(const uint8_t *bytes, size_t len, char *out, size_t out_len) {
    static const char hex[] = "0123456789abcdef";
    size_t i = 0;

    if (!out || out_len == 0) {
        return;
    }

    if (!bytes || out_len < (len * 2 + 1)) {
        out[0] = '\0';
        return;
    }

    for (i = 0; i < len; i++) {
        out[i * 2] = hex[(bytes[i] >> 4) & 0x0f];
        out[i * 2 + 1] = hex[bytes[i] & 0x0f];
    }
    out[len * 2] = '\0';
}

static int meshctl_parse_bool_arg(const char *value, int *out) {
    if (!value || !out) {
        return -1;
    }

    if (strcmp(value, "true") == 0 || strcmp(value, "1") == 0) {
        *out = 1;
        return 0;
    }

    if (strcmp(value, "false") == 0 || strcmp(value, "0") == 0) {
        *out = 0;
        return 0;
    }

    return -1;
}

static int meshctl_config_add_bootstrap(meshctl_config_t *cfg, const char *value) {
    if (!cfg || !value || cfg->bootstrap_count >= MESH_NODE_MAX_BOOTSTRAP_PEERS) {
        return -1;
    }

    strncpy(cfg->bootstrap_storage[cfg->bootstrap_count],
            value,
            sizeof(cfg->bootstrap_storage[cfg->bootstrap_count]) - 1);
    cfg->bootstrap_peers[cfg->bootstrap_count] = cfg->bootstrap_storage[cfg->bootstrap_count];
    cfg->bootstrap_count++;
    return 0;
}

static int meshctl_config_add_stun(meshctl_config_t *cfg, const char *value) {
    if (!cfg || !value || cfg->stun_count >= MESH_NODE_MAX_STUN_SERVERS) {
        return -1;
    }

    strncpy(cfg->stun_storage[cfg->stun_count],
            value,
            sizeof(cfg->stun_storage[cfg->stun_count]) - 1);
    cfg->stun_servers[cfg->stun_count] = cfg->stun_storage[cfg->stun_count];
    cfg->stun_count++;
    return 0;
}

static int meshctl_write_init_config(FILE *fp,
                                     const meshctl_config_t *cfg,
                                     const char *node_id_hex) {
    int i = 0;

    if (!fp || !cfg || !node_id_hex) {
        return -1;
    }

    fprintf(fp, "# generated by meshctl init\n");
    fprintf(fp, "# node_id: %s\n", node_id_hex);
    fprintf(fp, "# keep identity_secret_hex private\n");
    fprintf(fp, "node_name: %s\n", cfg->node_name);
    fprintf(fp, "network_id: %s\n", cfg->network_id);
    fprintf(fp, "# magic_dns_domain: %s.mesh\n", cfg->network_id);
    fprintf(fp, "# magic_dns_names:\n");
    fprintf(fp, "#   - %s=%s\n", cfg->node_name, cfg->virtual_ip);
    fprintf(fp, "virtual_ip: %s\n", cfg->virtual_ip);
    if (cfg->advertise_ip[0]) {
        fprintf(fp, "advertise_ip: %s\n", cfg->advertise_ip);
    }
    fprintf(fp, "virtual_prefix: %u\n", cfg->virtual_prefix);
    fprintf(fp, "identity_secret_hex: %s\n", cfg->identity_secret_hex);
    fprintf(fp, "listen_port: %d\n", cfg->listen_port);
    fprintf(fp, "ice_enabled: %s\n", cfg->ice_enabled ? "true" : "false");
    if (cfg->ice_allow_loopback) {
        fprintf(fp, "ice_allow_loopback: true\n");
    }

    if (cfg->bootstrap_count > 0) {
        fprintf(fp, "bootstrap_peers:\n");
        for (i = 0; i < cfg->bootstrap_count; i++) {
            fprintf(fp, "  - %s\n", cfg->bootstrap_peers[i]);
        }
    } else {
        fprintf(fp, "bootstrap_peers: []\n");
    }

    if (cfg->stun_count > 0) {
        fprintf(fp, "stun_servers:\n");
        for (i = 0; i < cfg->stun_count; i++) {
            fprintf(fp, "  - %s\n", cfg->stun_servers[i]);
        }
    } else {
        fprintf(fp, "stun_servers: []\n");
    }

    fprintf(fp, "# route_rules:\n");
    fprintf(fp, "#   - 10.42.0.3/32=10.42.0.1,pin\n");
    fprintf(fp, "# local_egress_cidrs:\n");
    fprintf(fp, "#   - 192.168.50.0/24\n");
    fprintf(fp, "# local_egress_allow_cidrs:\n");
    fprintf(fp, "#   - 10.42.0.0/16\n");
    fprintf(fp, "# packet_policy:\n");
    fprintf(fp, "#   - allow,out,src=%s/32,dst=10.42.0.1/32,proto=tcp,dport=443\n",
            cfg->virtual_ip);
    fprintf(fp, "#   - deny,out,dst=0.0.0.0/0\n");
    fprintf(fp, "# peer_allow_cidrs:\n");
    fprintf(fp, "#   - 10.42.0.1/32\n");
    fprintf(fp, "# peer_allow_node_ids:\n");
    fprintf(fp, "#   - %s\n", node_id_hex);
    fprintf(fp, "# peer_protocol_major: %d\n", MESH_PROTOCOL_MAJOR);
    return 0;
}

static int meshctl_path_exists(const char *path) {
    FILE *fp = NULL;

    if (!path || !*path) {
        return 0;
    }

    fp = fopen(path, "rb");
    if (!fp) {
        return 0;
    }

    fclose(fp);
    return 1;
}

static char *trim(char *s) {
    char *end = NULL;

    while (*s && isspace((unsigned char)*s)) {
        s++;
    }

    if (*s == '\0') {
        return s;
    }

    end = s + strlen(s) - 1;
    while (end > s && isspace((unsigned char)*end)) {
        *end-- = '\0';
    }

    return s;
}

static int parse_ipv4(const char *ip) {
    unsigned int a = 0;
    unsigned int b = 0;
    unsigned int c = 0;
    unsigned int d = 0;

    if (sscanf(ip, "%u.%u.%u.%u", &a, &b, &c, &d) != 4) {
        return 0;
    }

    return a <= 255 && b <= 255 && c <= 255 && d <= 255;
}

static uint64_t meshctl_now_ms(void) {
#ifdef _WIN32
    return (uint64_t)GetTickCount64();
#else
    struct timespec ts;
    clock_gettime(CLOCK_MONOTONIC, &ts);
    return (uint64_t)ts.tv_sec * 1000ULL + (uint64_t)(ts.tv_nsec / 1000000ULL);
#endif
}

static uint32_t parse_ipv4_be(const char *ip) {
    unsigned int a = 0;
    unsigned int b = 0;
    unsigned int c = 0;
    unsigned int d = 0;

    if (sscanf(ip, "%u.%u.%u.%u", &a, &b, &c, &d) != 4) {
        return 0;
    }

    return (uint32_t)((a & 0xffU) << 24) |
           (uint32_t)((b & 0xffU) << 16) |
           (uint32_t)((c & 0xffU) << 8) |
           (uint32_t)(d & 0xffU);
}

static void format_ipv4_be(uint32_t ip, char *buf, size_t buf_len) {
    snprintf(buf, buf_len, "%u.%u.%u.%u",
             (unsigned)((ip >> 24) & 0xffU),
             (unsigned)((ip >> 16) & 0xffU),
             (unsigned)((ip >> 8) & 0xffU),
             (unsigned)(ip & 0xffU));
}

static void meshctl_print_json_string(const char *value) {
    const unsigned char *p = (const unsigned char *)(value ? value : "");

    putchar('"');
    while (*p) {
        switch (*p) {
            case '\\':
                fputs("\\\\", stdout);
                break;
            case '"':
                fputs("\\\"", stdout);
                break;
            case '\b':
                fputs("\\b", stdout);
                break;
            case '\f':
                fputs("\\f", stdout);
                break;
            case '\n':
                fputs("\\n", stdout);
                break;
            case '\r':
                fputs("\\r", stdout);
                break;
            case '\t':
                fputs("\\t", stdout);
                break;
            default:
                if (*p < 0x20) {
                    printf("\\u%04x", (unsigned int)*p);
                } else {
                    putchar((int)*p);
                }
                break;
        }
        p++;
    }
    putchar('"');
}

static int meshctl_args_want_json(const char *args) {
    return args && (*args != '\0') &&
           (strcmp(args, "json") == 0 || strcmp(args, "--json") == 0 || strcmp(args, "-j") == 0);
}

static const char *meshctl_peer_state(int is_connected) {
    return is_connected ? "connected" : "disconnected";
}

static void meshctl_build_vip_dht_key(char *buf, size_t buf_len) {
    snprintf(buf, buf_len, "mesh:%s:ip:%s", g_config.network_id, g_config.virtual_ip);
}

static int meshctl_build_reverse_dht_key(char *buf, size_t buf_len) {
    if (!g_config.advertise_ip[0]) {
        return 0;
    }

    snprintf(buf, buf_len, "mesh:%s:peer:%s:%d",
             g_config.network_id, g_config.advertise_ip, g_config.listen_port);
    return 1;
}

static void meshctl_build_routes_dht_key(char *buf, size_t buf_len) {
    snprintf(buf, buf_len, "mesh:%s:routes:%s",
             g_config.network_id, g_config.virtual_ip);
}

static void meshctl_print_dht_known_entry_json(mesh_network_t *mesh,
                                               const char *label,
                                               const char *key) {
    char value[1024] = {0};
    size_t value_len = sizeof(value);
    int found = 0;

    printf("{\"label\":");
    meshctl_print_json_string(label);
    printf(",\"key\":");
    meshctl_print_json_string(key ? key : "");

    if (key && mesh_get_cached_dht_value(mesh, key, value, &value_len) == MESH_OK) {
        found = 1;
    }

    printf(",\"present\":%s", found ? "true" : "false");
    printf(",\"value\":");
    meshctl_print_json_string(found ? value : "");
    printf("}");
}

static void meshctl_print_dht_json_fields(mesh_network_t *mesh) {
    mesh_stats_t stats;
    char vip_key[128];
    char reverse_key[128];
    char routes_key[128];
    int emitted = 0;

    if (mesh_get_stats(mesh, &stats) != MESH_OK) {
        fprintf(stderr, "Failed to read mesh stats\n");
        return;
    }

    meshctl_build_vip_dht_key(vip_key, sizeof(vip_key));
    meshctl_build_routes_dht_key(routes_key, sizeof(routes_key));

    printf("\"dht\":{\"entry_count\":%u,\"known_entries\":[", stats.dht_entries);
    meshctl_print_dht_known_entry_json(mesh, "virtual_ip", vip_key);
    emitted = 1;

    if (meshctl_build_reverse_dht_key(reverse_key, sizeof(reverse_key))) {
        if (emitted) {
            putchar(',');
        }
        meshctl_print_dht_known_entry_json(mesh, "reverse_peer", reverse_key);
        emitted = 1;
    }

    if (emitted) {
        putchar(',');
    }
    meshctl_print_dht_known_entry_json(mesh, "routes", routes_key);
    printf("]}");
}

static void meshctl_print_dht_json(mesh_network_t *mesh) {
    printf("{");
    meshctl_print_dht_json_fields(mesh);
    printf("}\n");
}

static void meshctl_print_dht(mesh_network_t *mesh) {
    mesh_stats_t stats;
    char vip_key[128];
    char reverse_key[128];
    char routes_key[128];
    char value[1024];
    size_t value_len = 0;

    if (mesh_get_stats(mesh, &stats) != MESH_OK) {
        fprintf(stderr, "Failed to read mesh stats\n");
        return;
    }

    printf("[dht] entries=%u\n", stats.dht_entries);

    meshctl_build_vip_dht_key(vip_key, sizeof(vip_key));
    value_len = sizeof(value);
    if (mesh_get_cached_dht_value(mesh, vip_key, value, &value_len) == MESH_OK) {
        printf("[dht] virtual_ip key=%s value=%s\n", vip_key, value);
    } else {
        printf("[dht] virtual_ip key=%s value=(missing)\n", vip_key);
    }

    if (meshctl_build_reverse_dht_key(reverse_key, sizeof(reverse_key))) {
        value_len = sizeof(value);
        if (mesh_get_cached_dht_value(mesh, reverse_key, value, &value_len) == MESH_OK) {
            printf("[dht] reverse_peer key=%s value=%s\n", reverse_key, value);
        } else {
            printf("[dht] reverse_peer key=%s value=(missing)\n", reverse_key);
        }
    }

    meshctl_build_routes_dht_key(routes_key, sizeof(routes_key));
    value_len = sizeof(value);
    if (mesh_get_cached_dht_value(mesh, routes_key, value, &value_len) == MESH_OK) {
        printf("[dht] routes key=%s value=%s\n", routes_key, value[0] ? value : "(empty)");
    } else {
        printf("[dht] routes key=%s value=(missing)\n", routes_key);
    }
}

static int meshctl_get_health(mesh_network_t *mesh, mesh_runtime_health_t *health) {
    if (mesh_runtime_health_eval(mesh, g_config.bootstrap_count, health) != 0) {
        fprintf(stderr, "Failed to evaluate mesh health\n");
        return -1;
    }

    return 0;
}

static void meshctl_print_health_json_fields(mesh_network_t *mesh) {
    mesh_runtime_health_t health;

    if (meshctl_get_health(mesh, &health) != 0) {
        printf("\"health\":{\"state\":\"unhealthy\",\"reason\":\"no_connected_path\","
               "\"summary\":\"health unavailable\",\"path_mode\":\"isolated\","
               "\"signals\":{\"bootstrap_configured\":false,"
               "\"bootstrap_reconnect_pending\":false,"
               "\"has_direct_peer\":false,\"has_relay_path\":false,"
               "\"has_any_path\":false,\"ice_enabled\":false,"
               "\"ice_progressing\":false,\"ice_failed\":false}}");
        return;
    }

    printf("\"health\":{\"state\":");
    meshctl_print_json_string(mesh_runtime_health_state_string(health.state));
    printf(",\"reason\":");
    meshctl_print_json_string(mesh_runtime_health_reason_string(health.reason));
    printf(",\"summary\":");
    meshctl_print_json_string(mesh_runtime_health_summary(&health));
    printf(",\"path_mode\":");
    meshctl_print_json_string(mesh_path_mode_string(health.path_mode));
    printf(",\"signals\":{\"bootstrap_configured\":%s,"
           "\"bootstrap_reconnect_pending\":%s,"
           "\"has_direct_peer\":%s,\"has_relay_path\":%s,"
           "\"has_any_path\":%s,\"ice_enabled\":%s,"
           "\"ice_progressing\":%s,\"ice_failed\":%s}}",
           health.bootstrap_configured ? "true" : "false",
           health.bootstrap_reconnect_pending ? "true" : "false",
           health.has_direct_peer ? "true" : "false",
           health.has_relay_path ? "true" : "false",
           health.has_any_path ? "true" : "false",
           health.ice_enabled ? "true" : "false",
           health.ice_progressing ? "true" : "false",
           health.ice_failed ? "true" : "false");
}

static void meshctl_print_health(mesh_network_t *mesh) {
    mesh_runtime_health_t health;

    if (meshctl_get_health(mesh, &health) != 0) {
        printf("[health] state=unhealthy reason=no_connected_path "
               "path_mode=isolated direct=false relay=false any_path=false "
               "bootstrap_configured=false bootstrap_pending=false "
               "ice_enabled=false ice_progressing=false ice_failed=false "
               "summary=health unavailable\n");
        return;
    }

    printf("[health] state=%s reason=%s path_mode=%s "
           "direct=%s relay=%s any_path=%s "
           "bootstrap_configured=%s bootstrap_pending=%s "
           "ice_enabled=%s ice_progressing=%s ice_failed=%s "
           "summary=%s\n",
           mesh_runtime_health_state_string(health.state),
           mesh_runtime_health_reason_string(health.reason),
           mesh_path_mode_string(health.path_mode),
           health.has_direct_peer ? "true" : "false",
           health.has_relay_path ? "true" : "false",
           health.has_any_path ? "true" : "false",
           health.bootstrap_configured ? "true" : "false",
           health.bootstrap_reconnect_pending ? "true" : "false",
           health.ice_enabled ? "true" : "false",
           health.ice_progressing ? "true" : "false",
           health.ice_failed ? "true" : "false",
           mesh_runtime_health_summary(&health));
}

static void meshctl_print_diag_json_fields(mesh_network_t *mesh) {
    mesh_diag_info_t diag;

    if (mesh_get_diag_info(mesh, &diag) != MESH_OK) {
        fprintf(stderr, "Failed to read mesh diagnostics\n");
        return;
    }

    printf("\"diagnostics\":{\"path_mode\":");
    meshctl_print_json_string(mesh_path_mode_string(diag.path_mode));
    printf(",\"direct_peer_count\":%u,\"relay_route_count\":%u,"
           "\"connected_relay_route_count\":%u,"
           "\"bootstrap_connect_attempts\":%u,\"bootstrap_retry_rounds\":%u,"
           "\"bootstrap_reconnect_scheduled\":%u,"
           "\"bootstrap_reconnect_pending\":%s,"
           "\"reconnect_poll_count\":%u,"
           "\"direct_connect_attempts\":%u,\"direct_connect_started\":%u,"
           "\"peer_connect_events\":%u,\"peer_disconnect_events\":%u,"
           "\"control_plane_refreshes\":%u,\"last_reconnect_reason\":",
           diag.direct_peer_count,
           diag.relay_route_count,
           diag.connected_relay_route_count,
           diag.bootstrap_connect_attempts,
           diag.bootstrap_retry_rounds,
           diag.bootstrap_reconnect_scheduled,
           diag.bootstrap_reconnect_pending ? "true" : "false",
           diag.reconnect_poll_count,
           diag.direct_connect_attempts,
           diag.direct_connect_started,
           diag.peer_connect_events,
           diag.peer_disconnect_events,
           diag.control_plane_refreshes);
    meshctl_print_json_string(diag.last_reconnect_reason);
    printf(",\"last_direct_attempt_endpoint\":");
    meshctl_print_json_string(diag.last_direct_attempt_endpoint);
    printf(",\"last_active_relay_next_hop\":{\"virtual_ip\":");
    meshctl_print_json_string(diag.last_active_relay_next_hop_virtual_ip);
    printf(",\"real_endpoint\":");
    meshctl_print_json_string(diag.last_active_relay_next_hop_real_ip);
    printf("},\"ice\":{\"enabled\":%s,\"peer_count\":%u,\"connected_peer_count\":%u,"
           "\"auth_tx\":%u,\"auth_rx\":%u,\"candidate_tx\":%u,\"candidate_rx\":%u,"
           "\"eoc_tx\":%u,\"eoc_rx\":%u,\"checks_started\":%u,"
           "\"last_check_local_candidates\":%u,\"last_check_remote_candidates\":%u,"
           "\"last_state\":",
           diag.ice_enabled ? "true" : "false",
           diag.ice_peer_count,
           diag.ice_connected_peer_count,
           diag.ice_auth_messages_tx,
           diag.ice_auth_messages_rx,
           diag.ice_candidate_messages_tx,
           diag.ice_candidate_messages_rx,
           diag.ice_end_of_candidates_tx,
           diag.ice_end_of_candidates_rx,
           diag.ice_checks_started,
           diag.ice_last_check_local_candidate_count,
           diag.ice_last_check_remote_candidate_count);
    meshctl_print_json_string(diag.last_ice_state);
    printf(",\"last_selected_local_endpoint\":");
    meshctl_print_json_string(diag.last_ice_selected_local_endpoint);
    printf(",\"last_selected_remote_endpoint\":");
    meshctl_print_json_string(diag.last_ice_selected_remote_endpoint);
    printf("}}");
}

static void meshctl_print_control_plane_json(mesh_network_t *mesh,
                                             const mesh_stats_t *stats,
                                             int direct_peers,
                                             int relay_routes,
                                             int route_policy,
                                             int peer_admission,
                                             int peer_identity_admission,
                                             unsigned int peer_protocol_major_policy) {
    printf("\"control_plane\":{\"summary\":{\"direct_peers\":%d,\"relay_routes\":%d,"
           "\"route_policy\":%d,\"peer_admission\":%d,\"peer_identity_admission\":%d,"
           "\"peer_protocol_major_policy\":%u,\"peer_count\":%u,"
           "\"tx_packets\":%llu,\"rx_packets\":%llu,\"tx_bytes\":%llu,"
           "\"rx_bytes\":%llu,\"dht_entries\":%u},",
           direct_peers > 0 ? direct_peers : 0,
           relay_routes > 0 ? relay_routes : 0,
           route_policy > 0 ? route_policy : 0,
           peer_admission > 0 ? peer_admission : 0,
           peer_identity_admission > 0 ? peer_identity_admission : 0,
           peer_protocol_major_policy,
           stats->peer_count,
           (unsigned long long)stats->packets_tx,
           (unsigned long long)stats->packets_rx,
           (unsigned long long)stats->bytes_tx,
           (unsigned long long)stats->bytes_rx,
           stats->dht_entries);
    meshctl_print_dht_json_fields(mesh);
    printf(",");
    meshctl_print_health_json_fields(mesh);
    printf(",");
    meshctl_print_diag_json_fields(mesh);
    printf("}");
}

static void meshctl_print_diag_text(mesh_network_t *mesh) {
    mesh_diag_info_t diag;

    if (mesh_get_diag_info(mesh, &diag) != MESH_OK) {
        fprintf(stderr, "Failed to read mesh diagnostics\n");
        return;
    }

    printf("[diag] path_mode=%s direct=%u relay=%u relay_connected=%u "
           "bootstrap_connects=%u bootstrap_retries=%u bootstrap_scheduled=%u "
           "bootstrap_pending=%s reconnect_poll=%u direct_attempts=%u direct_started=%u "
           "peer_connected=%u peer_disconnected=%u control_refreshes=%u "
           "last_reconnect_reason=%s last_direct_endpoint=%s "
           "last_relay_vip=%s last_relay_real=%s "
           "ice_enabled=%s ice_peers=%u ice_connected=%u "
           "ice_auth_tx=%u ice_auth_rx=%u ice_candidate_tx=%u ice_candidate_rx=%u "
           "ice_eoc_tx=%u ice_eoc_rx=%u ice_checks_started=%u "
           "ice_last_check_local=%u ice_last_check_remote=%u "
           "ice_state=%s ice_local=%s ice_remote=%s\n",
           mesh_path_mode_string(diag.path_mode),
           diag.direct_peer_count,
           diag.relay_route_count,
           diag.connected_relay_route_count,
           diag.bootstrap_connect_attempts,
           diag.bootstrap_retry_rounds,
           diag.bootstrap_reconnect_scheduled,
           diag.bootstrap_reconnect_pending ? "true" : "false",
           diag.reconnect_poll_count,
           diag.direct_connect_attempts,
           diag.direct_connect_started,
           diag.peer_connect_events,
           diag.peer_disconnect_events,
           diag.control_plane_refreshes,
           diag.last_reconnect_reason[0] ? diag.last_reconnect_reason : "(none)",
           diag.last_direct_attempt_endpoint[0] ? diag.last_direct_attempt_endpoint : "(none)",
           diag.last_active_relay_next_hop_virtual_ip[0] ? diag.last_active_relay_next_hop_virtual_ip : "(none)",
           diag.last_active_relay_next_hop_real_ip[0] ? diag.last_active_relay_next_hop_real_ip : "(none)",
           diag.ice_enabled ? "true" : "false",
           diag.ice_peer_count,
           diag.ice_connected_peer_count,
           diag.ice_auth_messages_tx,
           diag.ice_auth_messages_rx,
           diag.ice_candidate_messages_tx,
           diag.ice_candidate_messages_rx,
           diag.ice_end_of_candidates_tx,
           diag.ice_end_of_candidates_rx,
           diag.ice_checks_started,
           diag.ice_last_check_local_candidate_count,
           diag.ice_last_check_remote_candidate_count,
           diag.last_ice_state[0] ? diag.last_ice_state : "(none)",
           diag.last_ice_selected_local_endpoint[0] ? diag.last_ice_selected_local_endpoint : "(none)",
           diag.last_ice_selected_remote_endpoint[0] ? diag.last_ice_selected_remote_endpoint : "(none)");
}

static void meshctl_print_status_json(mesh_network_t *mesh) {
    mesh_stats_t stats;
    char node_id[65] = {0};
    int direct_peers = mesh_get_peer_count(mesh);
    int relay_routes = mesh_get_route_count(mesh);
    int route_policy = mesh_get_route_rule_count(mesh);
    int peer_admission = mesh_get_peer_allow_count(mesh);
    int peer_identity_admission = mesh_get_peer_allow_node_id_count(mesh);
    unsigned int peer_protocol_major_policy = mesh_get_peer_protocol_major(mesh);

    if (mesh_get_stats(mesh, &stats) != MESH_OK) {
        fprintf(stderr, "Failed to read mesh stats\n");
        return;
    }
    if (mesh_get_node_id(mesh, node_id, sizeof(node_id)) != MESH_OK) {
        node_id[0] = '\0';
    }

    printf("{\"snapshot_version\":%d,\"node\":", MESH_SNAPSHOT_VERSION);
    meshctl_print_json_string(g_config.node_name);
    printf(",\"network_id\":");
    meshctl_print_json_string(g_config.network_id);
    printf(",\"virtual_ip\":");
    meshctl_print_json_string(g_config.virtual_ip);
    printf(",\"virtual_prefix\":%u", g_config.virtual_prefix);
    printf(",\"advertise_ip\":");
    meshctl_print_json_string(g_config.advertise_ip[0] ? g_config.advertise_ip : "");
    printf(",\"identity_configured\":%s",
           g_config.identity_secret_hex[0] ? "true" : "false");
    printf(",\"node_id\":");
    meshctl_print_json_string(node_id);
    printf(",\"listen_port\":%d", g_config.listen_port);
    printf(",\"protocol_major\":%u", (unsigned int)MESH_PROTOCOL_MAJOR);
    printf(",\"protocol_minor\":%u", (unsigned int)MESH_PROTOCOL_MINOR);
    printf(",\"bootstrap_peers\":%d", g_config.bootstrap_count);
    printf(",\"direct_peers\":%d", direct_peers > 0 ? direct_peers : 0);
    printf(",\"relay_routes\":%d", relay_routes > 0 ? relay_routes : 0);
    printf(",\"route_policy\":%d", route_policy > 0 ? route_policy : 0);
    printf(",\"peer_admission\":%d", peer_admission > 0 ? peer_admission : 0);
    printf(",\"peer_identity_admission\":%d", peer_identity_admission > 0 ? peer_identity_admission : 0);
    printf(",\"peer_protocol_major_policy\":%u", peer_protocol_major_policy);
    printf(",");
    meshctl_print_health_json_fields(mesh);
    printf(",\"stats\":{\"peer_count\":%u,\"tx_packets\":%llu,\"rx_packets\":%llu,"
           "\"tx_bytes\":%llu,\"rx_bytes\":%llu,\"dht_entries\":%u},",
           stats.peer_count,
           (unsigned long long)stats.packets_tx,
           (unsigned long long)stats.packets_rx,
           (unsigned long long)stats.bytes_tx,
           (unsigned long long)stats.bytes_rx,
           stats.dht_entries);
    meshctl_print_dht_json_fields(mesh);
    printf(",");
    meshctl_print_diag_json_fields(mesh);
    printf(",");
    meshctl_print_control_plane_json(mesh, &stats, direct_peers, relay_routes, route_policy,
                                     peer_admission, peer_identity_admission,
                                     peer_protocol_major_policy);
    printf("}\n");
}

static void meshctl_print_status(mesh_network_t *mesh) {
    mesh_stats_t stats;
    mesh_diag_info_t diag;
    mesh_runtime_health_t health;
    int route_policy = mesh_get_route_rule_count(mesh);
    int peer_admission = mesh_get_peer_allow_count(mesh);
    int peer_identity_admission = mesh_get_peer_allow_node_id_count(mesh);
    unsigned int peer_protocol_major_policy = mesh_get_peer_protocol_major(mesh);

    if (mesh_get_stats(mesh, &stats) != MESH_OK) {
        fprintf(stderr, "Failed to read mesh stats\n");
        return;
    }
    if (mesh_get_diag_info(mesh, &diag) != MESH_OK) {
        fprintf(stderr, "Failed to read mesh diagnostics\n");
        return;
    }
    if (meshctl_get_health(mesh, &health) != 0) {
        return;
    }

    printf("[status] node=%s vip=%s/%u peers=%u relay_routes=%u route_policy=%d peer_admission=%d "
           "peer_identity_admission=%d peer_protocol_major_policy=%u path_mode=%s "
           "health=%s reason=%s "
           "tx_packets=%llu rx_packets=%llu tx_bytes=%llu rx_bytes=%llu dht=%u\n",
           g_config.node_name,
           g_config.virtual_ip,
           g_config.virtual_prefix,
           stats.peer_count,
           diag.relay_route_count,
           route_policy,
           peer_admission,
           peer_identity_admission,
           peer_protocol_major_policy,
           mesh_path_mode_string(diag.path_mode),
           mesh_runtime_health_state_string(health.state),
           mesh_runtime_health_reason_string(health.reason),
           (unsigned long long)stats.packets_tx,
           (unsigned long long)stats.packets_rx,
           (unsigned long long)stats.bytes_tx,
           (unsigned long long)stats.bytes_rx,
           stats.dht_entries);
}

static void meshctl_print_peers_json(mesh_network_t *mesh) {
    int count = mesh_get_peer_count(mesh);
    int i = 0;
    int emitted = 0;

    printf("{\"direct_peers\":[");
    for (i = 0; i < count; i++) {
        mesh_peer_info_t info;

        if (mesh_get_peer_info(mesh, i, &info) != MESH_OK) {
            continue;
        }

        if (emitted > 0) {
            putchar(',');
        }
        emitted++;

        printf("{\"index\":%d,\"type\":\"direct\",\"virtual_ip\":", i);
        meshctl_print_json_string(info.virtual_ip);
        printf(",\"real_endpoint\":");
        meshctl_print_json_string(info.real_ip);
        printf(",\"node_id\":");
        meshctl_print_json_string(info.node_id);
        printf(",\"protocol_major\":%u,\"protocol_minor\":%u",
               (unsigned int)info.protocol_major,
               (unsigned int)info.protocol_minor);
        printf(",\"state\":\"%s\",\"is_connected\":%s,\"tx_bytes\":%llu,"
               "\"rx_bytes\":%llu,\"last_seen_ms\":%llu}",
               meshctl_peer_state(info.is_connected),
               info.is_connected ? "true" : "false",
               (unsigned long long)info.bytes_tx,
               (unsigned long long)info.bytes_rx,
               (unsigned long long)info.last_seen_ms);
    }
    printf("]}\n");
}

static void meshctl_print_peers(mesh_network_t *mesh) {
    int count = mesh_get_peer_count(mesh);
    int i = 0;

    if (count <= 0) {
        printf("[peers] no peers connected\n");
        return;
    }

    for (i = 0; i < count; i++) {
        mesh_peer_info_t info;
        if (mesh_get_peer_info(mesh, i, &info) != MESH_OK) {
            continue;
        }

        printf("[peer %d] type=direct vip=%s real=%s node_id=%s protocol=%u.%u state=%s tx=%llu rx=%llu last_seen_ms=%llu\n",
               i,
               info.virtual_ip,
               info.real_ip,
               info.node_id[0] ? info.node_id : "(unknown)",
               (unsigned int)info.protocol_major,
               (unsigned int)info.protocol_minor,
               info.is_connected ? "connected" : "disconnected",
               (unsigned long long)info.bytes_tx,
               (unsigned long long)info.bytes_rx,
               (unsigned long long)info.last_seen_ms);
    }
}

static void meshctl_print_routes_json(mesh_network_t *mesh) {
    int count = mesh_get_route_count(mesh);
    int i = 0;
    int emitted = 0;

    printf("{\"relay_routes\":[");
    for (i = 0; i < count; i++) {
        mesh_route_info_t info;

        if (mesh_get_route_info(mesh, i, &info) != MESH_OK) {
            continue;
        }

        if (emitted > 0) {
            putchar(',');
        }
        emitted++;

        printf("{\"index\":%d,\"type\":\"relay\",\"dest_ip\":", i);
        meshctl_print_json_string(info.dest_ip);
        printf(",\"dest_real_endpoint\":");
        meshctl_print_json_string(info.dest_real_ip);
        printf(",\"next_hop_virtual_ip\":");
        meshctl_print_json_string(info.next_hop_virtual_ip);
        printf(",\"next_hop_real_endpoint\":");
        meshctl_print_json_string(info.next_hop_real_ip);
        printf(",\"hop_count\":%u,\"state\":\"%s\",\"is_connected\":%s,"
               "\"last_update_ms\":%llu}",
               (unsigned int)info.hop_count,
               meshctl_peer_state(info.is_connected),
               info.is_connected ? "true" : "false",
               (unsigned long long)info.last_update_ms);
    }
    printf("]}\n");
}

static void meshctl_print_routes(mesh_network_t *mesh) {
    int count = mesh_get_route_count(mesh);
    int i = 0;

    if (count <= 0) {
        printf("[routes] no learned routes\n");
        return;
    }

    for (i = 0; i < count; i++) {
        mesh_route_info_t info;
        if (mesh_get_route_info(mesh, i, &info) != MESH_OK) {
            continue;
        }

        printf("[route %d] dest=%s dest_real=%s via=%s next_real=%s hops=%u state=%s last_update_ms=%llu\n",
               i,
               info.dest_ip,
               info.dest_real_ip,
               info.next_hop_virtual_ip,
               info.next_hop_real_ip,
               (unsigned)info.hop_count,
               info.is_connected ? "connected" : "disconnected",
               (unsigned long long)info.last_update_ms);
    }
}

static void meshctl_print_policy_json(mesh_network_t *mesh) {
    int count = mesh_get_route_rule_count(mesh);
    int i = 0;
    int emitted = 0;

    printf("{\"route_policy\":[");
    for (i = 0; i < count; i++) {
        mesh_route_rule_info_t info;

        if (mesh_get_route_rule_info(mesh, i, &info) != MESH_OK) {
            continue;
        }

        if (emitted > 0) {
            putchar(',');
        }
        emitted++;

        printf("{\"index\":%d,\"dest_cidr\":", i);
        meshctl_print_json_string(info.dest_cidr);
        printf(",\"next_hop_virtual_ip\":");
        meshctl_print_json_string(info.next_hop_virtual_ip);
        printf(",\"flags\":[");
        if (info.flags & MESH_ROUTE_RULE_PINNED) {
            meshctl_print_json_string("pin");
        }
        printf("]}");
    }
    printf("]}\n");
}

static void meshctl_print_policy(mesh_network_t *mesh) {
    int count = mesh_get_route_rule_count(mesh);
    int i = 0;

    if (count <= 0) {
        printf("[policy] no configured route policy\n");
        return;
    }

    for (i = 0; i < count; i++) {
        mesh_route_rule_info_t info;
        if (mesh_get_route_rule_info(mesh, i, &info) != MESH_OK) {
            continue;
        }

        printf("[policy %d] dest=%s via=%s flags=%s\n",
               i,
               info.dest_cidr,
               info.next_hop_virtual_ip,
               (info.flags & MESH_ROUTE_RULE_PINNED) ? "pin" : "none");
    }
}

static void meshctl_print_admission_json(mesh_network_t *mesh) {
    int count = mesh_get_peer_allow_count(mesh);
    int node_id_count = mesh_get_peer_allow_node_id_count(mesh);
    unsigned int peer_protocol_major_policy = mesh_get_peer_protocol_major(mesh);
    int i = 0;
    int emitted = 0;

    printf("{\"peer_admission\":{\"cidrs\":[");
    for (i = 0; i < count; i++) {
        mesh_peer_allow_info_t info;

        if (mesh_get_peer_allow_info(mesh, i, &info) != MESH_OK) {
            continue;
        }

        if (emitted > 0) {
            putchar(',');
        }
        emitted++;

        printf("{\"index\":%d,\"cidr\":", i);
        meshctl_print_json_string(info.cidr);
        printf("}");
    }
    printf("],\"node_ids\":[");
    emitted = 0;
    for (i = 0; i < node_id_count; i++) {
        mesh_peer_allow_node_info_t info;

        if (mesh_get_peer_allow_node_info(mesh, i, &info) != MESH_OK) {
            continue;
        }

        if (emitted > 0) {
            putchar(',');
        }
        emitted++;

        printf("{\"index\":%d,\"node_id\":", i);
        meshctl_print_json_string(info.node_id);
        printf("}");
    }
    printf("],\"protocol_major\":%u}}\n", peer_protocol_major_policy);
}

static void meshctl_print_admission(mesh_network_t *mesh) {
    int count = mesh_get_peer_allow_count(mesh);
    int node_id_count = mesh_get_peer_allow_node_id_count(mesh);
    unsigned int peer_protocol_major_policy = mesh_get_peer_protocol_major(mesh);
    int i = 0;

    if (count <= 0 && node_id_count <= 0 && peer_protocol_major_policy == 0) {
        printf("[admission] no configured peer allowlist\n");
        return;
    }

    for (i = 0; i < count; i++) {
        mesh_peer_allow_info_t info;
        if (mesh_get_peer_allow_info(mesh, i, &info) != MESH_OK) {
            continue;
        }

        printf("[admission %d] allow=%s\n", i, info.cidr);
    }

    for (i = 0; i < node_id_count; i++) {
        mesh_peer_allow_node_info_t info;
        if (mesh_get_peer_allow_node_info(mesh, i, &info) != MESH_OK) {
            continue;
        }

        printf("[admission node_id %d] allow=%s\n", i, info.node_id);
    }

    if (peer_protocol_major_policy > 0) {
        printf("[admission protocol] require_major=%u\n", peer_protocol_major_policy);
    } else {
        printf("[admission protocol] require_major=any\n");
    }
}

static void meshctl_print_dump_json(mesh_network_t *mesh) {
    mesh_stats_t stats;
    char node_id[65] = {0};
    int peer_count = mesh_get_peer_count(mesh);
    int route_count = mesh_get_route_count(mesh);
    int policy_count = mesh_get_route_rule_count(mesh);
    int admission_count = mesh_get_peer_allow_count(mesh);
    int identity_admission_count = mesh_get_peer_allow_node_id_count(mesh);
    unsigned int peer_protocol_major_policy = mesh_get_peer_protocol_major(mesh);
    int i = 0;
    int emitted = 0;

    if (mesh_get_stats(mesh, &stats) != MESH_OK) {
        fprintf(stderr, "Failed to read mesh stats\n");
        return;
    }
    if (mesh_get_node_id(mesh, node_id, sizeof(node_id)) != MESH_OK) {
        node_id[0] = '\0';
    }

    printf("{\"snapshot_version\":%d,\"node\":{", MESH_SNAPSHOT_VERSION);
    printf("\"name\":");
    meshctl_print_json_string(g_config.node_name);
    printf(",\"network_id\":");
    meshctl_print_json_string(g_config.network_id);
    printf(",\"virtual_ip\":");
    meshctl_print_json_string(g_config.virtual_ip);
    printf(",\"virtual_prefix\":%u", g_config.virtual_prefix);
    printf(",\"advertise_ip\":");
    meshctl_print_json_string(g_config.advertise_ip[0] ? g_config.advertise_ip : "");
    printf(",\"identity_configured\":%s",
           g_config.identity_secret_hex[0] ? "true" : "false");
    printf(",\"node_id\":");
    meshctl_print_json_string(node_id);
    printf(",\"listen_port\":%d", g_config.listen_port);
    printf(",\"protocol_major\":%u", (unsigned int)MESH_PROTOCOL_MAJOR);
    printf(",\"protocol_minor\":%u", (unsigned int)MESH_PROTOCOL_MINOR);
    printf(",\"bootstrap_peers\":[");
    for (i = 0; i < g_config.bootstrap_count; i++) {
        if (i > 0) {
            putchar(',');
        }
        meshctl_print_json_string(g_config.bootstrap_peers[i]);
    }
    printf("]},\"status\":{\"direct_peers\":%d,\"relay_routes\":%d,"
           "\"route_policy\":%d,\"peer_admission\":%d,\"tx_packets\":%llu,\"rx_packets\":%llu,\"tx_bytes\":%llu,"
           "\"rx_bytes\":%llu,\"dht_entries\":%u,\"peer_identity_admission\":%d,\"peer_protocol_major_policy\":%u},",
           peer_count > 0 ? peer_count : 0,
           route_count > 0 ? route_count : 0,
           policy_count > 0 ? policy_count : 0,
           admission_count > 0 ? admission_count : 0,
           (unsigned long long)stats.packets_tx,
           (unsigned long long)stats.packets_rx,
           (unsigned long long)stats.bytes_tx,
           (unsigned long long)stats.bytes_rx,
           stats.dht_entries,
           identity_admission_count > 0 ? identity_admission_count : 0,
           peer_protocol_major_policy);
    meshctl_print_dht_json_fields(mesh);
    printf(",");
    meshctl_print_health_json_fields(mesh);
    printf(",");
    meshctl_print_diag_json_fields(mesh);
    printf(",");
    meshctl_print_control_plane_json(mesh, &stats, peer_count, route_count, policy_count,
                                     admission_count, identity_admission_count,
                                     peer_protocol_major_policy);
    printf(",\"direct_peers\":[");

    for (i = 0; i < peer_count; i++) {
        mesh_peer_info_t info;

        if (mesh_get_peer_info(mesh, i, &info) != MESH_OK) {
            continue;
        }

        if (emitted > 0) {
            putchar(',');
        }
        emitted++;

        printf("{\"index\":%d,\"type\":\"direct\",\"virtual_ip\":", i);
        meshctl_print_json_string(info.virtual_ip);
        printf(",\"real_endpoint\":");
        meshctl_print_json_string(info.real_ip);
        printf(",\"node_id\":");
        meshctl_print_json_string(info.node_id);
        printf(",\"protocol_major\":%u,\"protocol_minor\":%u",
               (unsigned int)info.protocol_major,
               (unsigned int)info.protocol_minor);
        printf(",\"state\":\"%s\",\"is_connected\":%s,\"tx_bytes\":%llu,"
               "\"rx_bytes\":%llu,\"last_seen_ms\":%llu}",
               meshctl_peer_state(info.is_connected),
               info.is_connected ? "true" : "false",
               (unsigned long long)info.bytes_tx,
               (unsigned long long)info.bytes_rx,
               (unsigned long long)info.last_seen_ms);
    }

    printf("],\"relay_routes\":[");
    emitted = 0;
    for (i = 0; i < route_count; i++) {
        mesh_route_info_t info;

        if (mesh_get_route_info(mesh, i, &info) != MESH_OK) {
            continue;
        }

        if (emitted > 0) {
            putchar(',');
        }
        emitted++;

        printf("{\"index\":%d,\"type\":\"relay\",\"dest_ip\":", i);
        meshctl_print_json_string(info.dest_ip);
        printf(",\"dest_real_endpoint\":");
        meshctl_print_json_string(info.dest_real_ip);
        printf(",\"next_hop_virtual_ip\":");
        meshctl_print_json_string(info.next_hop_virtual_ip);
        printf(",\"next_hop_real_endpoint\":");
        meshctl_print_json_string(info.next_hop_real_ip);
        printf(",\"hop_count\":%u,\"state\":\"%s\",\"is_connected\":%s,"
               "\"last_update_ms\":%llu}",
               (unsigned int)info.hop_count,
               meshctl_peer_state(info.is_connected),
               info.is_connected ? "true" : "false",
               (unsigned long long)info.last_update_ms);
    }
    printf("],\"route_policy\":[");
    emitted = 0;
    for (i = 0; i < policy_count; i++) {
        mesh_route_rule_info_t info;

        if (mesh_get_route_rule_info(mesh, i, &info) != MESH_OK) {
            continue;
        }

        if (emitted > 0) {
            putchar(',');
        }
        emitted++;

        printf("{\"index\":%d,\"dest_cidr\":", i);
        meshctl_print_json_string(info.dest_cidr);
        printf(",\"next_hop_virtual_ip\":");
        meshctl_print_json_string(info.next_hop_virtual_ip);
        printf(",\"flags\":[");
        if (info.flags & MESH_ROUTE_RULE_PINNED) {
            meshctl_print_json_string("pin");
        }
        printf("]}");
    }
    printf("],\"peer_admission\":{\"cidrs\":[");
    emitted = 0;
    for (i = 0; i < admission_count; i++) {
        mesh_peer_allow_info_t info;

        if (mesh_get_peer_allow_info(mesh, i, &info) != MESH_OK) {
            continue;
        }

        if (emitted > 0) {
            putchar(',');
        }
        emitted++;

        printf("{\"index\":%d,\"cidr\":", i);
        meshctl_print_json_string(info.cidr);
        printf("}");
    }
    printf("],\"node_ids\":[");
    emitted = 0;
    for (i = 0; i < identity_admission_count; i++) {
        mesh_peer_allow_node_info_t info;

        if (mesh_get_peer_allow_node_info(mesh, i, &info) != MESH_OK) {
            continue;
        }

        if (emitted > 0) {
            putchar(',');
        }
        emitted++;

        printf("{\"index\":%d,\"node_id\":", i);
        meshctl_print_json_string(info.node_id);
        printf("}");
    }
    printf("],\"protocol_major\":%u}}\n", peer_protocol_major_policy);
}

static void meshctl_print_dump(mesh_network_t *mesh) {
    mesh_stats_t stats;
    int peer_count = mesh_get_peer_count(mesh);
    int route_count = mesh_get_route_count(mesh);

    if (mesh_get_stats(mesh, &stats) != MESH_OK) {
        fprintf(stderr, "Failed to read mesh stats\n");
        return;
    }

    printf("[dump] node=%s network=%s vip=%s/%u advertise=%s listen=%d bootstrap=%d "
           "identity=%s "
           "direct_peers=%d relay_routes=%d route_policy=%d peer_admission=%d peer_identity_admission=%d peer_protocol_major_policy=%u tx_packets=%llu rx_packets=%llu "
           "tx_bytes=%llu rx_bytes=%llu dht=%u\n",
           g_config.node_name,
           g_config.network_id,
           g_config.virtual_ip,
           g_config.virtual_prefix,
           g_config.advertise_ip[0] ? g_config.advertise_ip : "(unset)",
           g_config.listen_port,
           g_config.bootstrap_count,
           g_config.identity_secret_hex[0] ? "configured" : "ephemeral",
           peer_count > 0 ? peer_count : 0,
           route_count > 0 ? route_count : 0,
           mesh_get_route_rule_count(mesh),
           mesh_get_peer_allow_count(mesh),
           mesh_get_peer_allow_node_id_count(mesh),
           mesh_get_peer_protocol_major(mesh),
           (unsigned long long)stats.packets_tx,
           (unsigned long long)stats.packets_rx,
           (unsigned long long)stats.bytes_tx,
           (unsigned long long)stats.bytes_rx,
           stats.dht_entries);
    meshctl_print_dht(mesh);
    meshctl_print_health(mesh);
    meshctl_print_diag_text(mesh);
    meshctl_print_peers(mesh);
    meshctl_print_routes(mesh);
    meshctl_print_policy(mesh);
    meshctl_print_admission(mesh);
}

static void meshctl_print_help(void) {
    printf("Commands:\n");
    printf("  status [json]     Show node statistics\n");
    printf("  health [json]     Show automation-friendly health state\n");
    printf("  dht [json]        Show cached mesh control-plane DHT entries\n");
    printf("  peers [json]      List direct peers\n");
    printf("  routes [json]     List learned relay routes\n");
    printf("  policy [json]     List configured route policy rules\n");
    printf("  admission [json]  List configured peer admission allowlist\n");
    printf("  dump [json]       Export status, peers, and routes together\n");
    printf("  diag [json]       Alias for dump\n");
    printf("  ping [virtual-ip] Send a test packet to a peer\n");
    printf("  help              Show this help\n");
    printf("  quit              Stop meshctl\n");
}

static int meshctl_build_ping_packet(const char *src_ip,
                                     const char *dst_ip,
                                     uint8_t *packet,
                                     size_t packet_len,
                                     size_t *out_len,
                                     int is_reply,
                                     unsigned int seq,
                                     uint64_t sent_ms) {
    char payload[96];
    size_t payload_len = 0;
    uint32_t src = parse_ipv4_be(src_ip);
    uint32_t dst = parse_ipv4_be(dst_ip);

    payload_len = (size_t)snprintf(payload, sizeof(payload),
                                   "%s:%u:%llu",
                                   is_reply ? "meshctl-pong" : "meshctl-ping",
                                   seq,
                                   (unsigned long long)sent_ms);
    if (payload_len >= sizeof(payload)) {
        return -1;
    }

    {
        size_t total_len = 20 + payload_len;

        if (!src || !dst || !packet || !out_len || packet_len < total_len) {
            return -1;
        }

        memset(packet, 0, total_len);
        packet[0] = 0x45;
        packet[2] = (uint8_t)((total_len >> 8) & 0xffU);
        packet[3] = (uint8_t)(total_len & 0xffU);
        packet[8] = 64;
        packet[9] = 253; /* Experimental protocol, enough for mesh routing tests. */
        packet[12] = (uint8_t)((src >> 24) & 0xffU);
        packet[13] = (uint8_t)((src >> 16) & 0xffU);
        packet[14] = (uint8_t)((src >> 8) & 0xffU);
        packet[15] = (uint8_t)(src & 0xffU);
        packet[16] = (uint8_t)((dst >> 24) & 0xffU);
        packet[17] = (uint8_t)((dst >> 16) & 0xffU);
        packet[18] = (uint8_t)((dst >> 8) & 0xffU);
        packet[19] = (uint8_t)(dst & 0xffU);
        memcpy(packet + 20, payload, payload_len);
        *out_len = total_len;
    }
    return 0;
}

static int meshctl_pick_ping_target(mesh_network_t *mesh, char *target, size_t target_len) {
    mesh_peer_info_t info;

    if (mesh_get_peer_count(mesh) <= 0) {
        return -1;
    }

    if (mesh_get_peer_info(mesh, 0, &info) != MESH_OK || !info.is_connected) {
        return -1;
    }

    strncpy(target, info.virtual_ip, target_len - 1);
    target[target_len - 1] = '\0';
    return 0;
}

static void meshctl_send_ping(mesh_network_t *mesh, const char *target_ip) {
    uint8_t packet[128];
    size_t packet_len = 0;
    int ret = 0;
    unsigned int seq = 0;
    uint64_t now_ms = 0;

    if (!target_ip || !parse_ipv4(target_ip)) {
        fprintf(stderr, "Invalid ping target: %s\n", target_ip ? target_ip : "(null)");
        return;
    }

    seq = ++g_ping_seq;
    now_ms = meshctl_now_ms();

    if (meshctl_build_ping_packet(g_config.virtual_ip, target_ip, packet, sizeof(packet),
                                  &packet_len, 0, seq, now_ms) != 0) {
        fprintf(stderr, "Failed to build ping packet\n");
        return;
    }

    ret = mesh_send_packet(mesh, packet, packet_len);
    if (ret != MESH_OK) {
        fprintf(stderr, "Ping send failed: %s\n", mesh_error_string((mesh_error_t)ret));
        return;
    }

    g_last_ping_seq = seq;
    g_last_ping_sent_ms = now_ms;
    strncpy(g_last_ping_target, target_ip, sizeof(g_last_ping_target) - 1);
    g_last_ping_target[sizeof(g_last_ping_target) - 1] = '\0';

    printf("[ping] seq=%u sent %zu bytes from %s to %s\n",
           seq, packet_len, g_config.virtual_ip, target_ip);
}

static void meshctl_handle_command(mesh_network_t *mesh, char *command) {
    char *args = NULL;

    command = trim(command);
    if (*command == '\0') {
        return;
    }

    args = strchr(command, ' ');
    if (args) {
        *args = '\0';
        args = trim(args + 1);
    }

    if (strcmp(command, "status") == 0) {
        if (meshctl_args_want_json(args)) {
            meshctl_print_status_json(mesh);
        } else {
            meshctl_print_status(mesh);
        }
        return;
    }

    if (strcmp(command, "health") == 0) {
        if (meshctl_args_want_json(args)) {
            printf("{");
            meshctl_print_health_json_fields(mesh);
            printf("}\n");
        } else {
            meshctl_print_health(mesh);
        }
        return;
    }

    if (strcmp(command, "dht") == 0) {
        if (meshctl_args_want_json(args)) {
            meshctl_print_dht_json(mesh);
        } else {
            meshctl_print_dht(mesh);
        }
        return;
    }

    if (strcmp(command, "peers") == 0) {
        if (meshctl_args_want_json(args)) {
            meshctl_print_peers_json(mesh);
        } else {
            meshctl_print_peers(mesh);
        }
        return;
    }

    if (strcmp(command, "routes") == 0) {
        if (meshctl_args_want_json(args)) {
            meshctl_print_routes_json(mesh);
        } else {
            meshctl_print_routes(mesh);
        }
        return;
    }

    if (strcmp(command, "policy") == 0) {
        if (meshctl_args_want_json(args)) {
            meshctl_print_policy_json(mesh);
        } else {
            meshctl_print_policy(mesh);
        }
        return;
    }

    if (strcmp(command, "admission") == 0) {
        if (meshctl_args_want_json(args)) {
            meshctl_print_admission_json(mesh);
        } else {
            meshctl_print_admission(mesh);
        }
        return;
    }

    if (strcmp(command, "dump") == 0 || strcmp(command, "diag") == 0) {
        if (meshctl_args_want_json(args)) {
            meshctl_print_dump_json(mesh);
        } else {
            meshctl_print_dump(mesh);
        }
        return;
    }

    if (strcmp(command, "help") == 0) {
        meshctl_print_help();
        return;
    }

    if (strcmp(command, "quit") == 0 || strcmp(command, "exit") == 0) {
        g_running = 0;
        return;
    }

    if (strcmp(command, "ping") == 0) {
        char target[16] = {0};

        if (args && *args) {
            strncpy(target, args, sizeof(target) - 1);
        } else if (meshctl_pick_ping_target(mesh, target, sizeof(target)) != 0) {
            fprintf(stderr, "No connected peer available for ping\n");
            return;
        }

        meshctl_send_ping(mesh, target);
        return;
    }

    fprintf(stderr, "Unknown command: %s\n", command);
    meshctl_print_help();
}

static void meshctl_command_queue_init(meshctl_command_queue_t *queue) {
    memset(queue, 0, sizeof(*queue));
    turbo_mutex_init(&queue->mutex);
}

static void meshctl_command_queue_destroy(meshctl_command_queue_t *queue) {
    turbo_mutex_destroy(&queue->mutex);
}

static int meshctl_command_queue_push(meshctl_command_queue_t *queue, const char *command) {
    int accepted = 0;

    turbo_mutex_lock(&queue->mutex);
    if (queue->count < MESHCTL_COMMAND_QUEUE_SIZE && !queue->stop) {
        strncpy(queue->commands[queue->tail], command, MESHCTL_MAX_COMMAND - 1);
        queue->commands[queue->tail][MESHCTL_MAX_COMMAND - 1] = '\0';
        queue->tail = (queue->tail + 1) % MESHCTL_COMMAND_QUEUE_SIZE;
        queue->count++;
        accepted = 1;
    }
    turbo_mutex_unlock(&queue->mutex);
    return accepted;
}

static int meshctl_command_queue_pop(meshctl_command_queue_t *queue, char *command, size_t command_len) {
    int has_command = 0;

    turbo_mutex_lock(&queue->mutex);
    if (queue->count > 0) {
        strncpy(command, queue->commands[queue->head], command_len - 1);
        command[command_len - 1] = '\0';
        queue->commands[queue->head][0] = '\0';
        queue->head = (queue->head + 1) % MESHCTL_COMMAND_QUEUE_SIZE;
        queue->count--;
        has_command = 1;
    }
    turbo_mutex_unlock(&queue->mutex);
    return has_command;
}

static int meshctl_command_queue_has_pending(meshctl_command_queue_t *queue) {
    int has_pending = 0;

    turbo_mutex_lock(&queue->mutex);
    has_pending = queue->count > 0;
    turbo_mutex_unlock(&queue->mutex);
    return has_pending;
}

static void meshctl_command_queue_stop(meshctl_command_queue_t *queue) {
    turbo_mutex_lock(&queue->mutex);
    queue->stop = 1;
    turbo_mutex_unlock(&queue->mutex);
}

static void meshctl_stdin_thread(void *arg) {
    meshctl_command_queue_t *queue = (meshctl_command_queue_t *)arg;
    char line[MESHCTL_MAX_COMMAND];

    while (g_running) {
        if (!fgets(line, sizeof(line), stdin)) {
            meshctl_command_queue_stop(queue);
            g_running = 0;
            break;
        }

        line[strcspn(line, "\r\n")] = '\0';
        if (!meshctl_command_queue_push(queue, line)) {
            fprintf(stderr, "Command dropped, queue is full\n");
        }

        if (strcmp(line, "quit") == 0 || strcmp(line, "exit") == 0) {
            break;
        }
    }
}

static void on_peer_connected(mesh_peer_t *peer, void *user_data) {
    mesh_peer_info_t info;

    (void)user_data;

    if (!g_mesh) {
        return;
    }

    if (mesh_get_peer_handle_info(peer, &info) == MESH_OK) {
        printf("[event] peer connected: vip=%s real=%s\n", info.virtual_ip, info.real_ip);
    } else {
        printf("[event] peer connected\n");
    }
}

static void on_peer_disconnected(mesh_peer_t *peer, void *user_data) {
    (void)peer;
    (void)user_data;
    printf("[event] peer disconnected\n");
}

static void on_packet_received(const uint8_t *data, size_t len, void *user_data) {
    char src[16];
    char dst[16];
    char payload[64];
    char kind[16];
    size_t payload_len = 0;
    uint32_t src_ip = 0;
    uint32_t dst_ip = 0;
    unsigned int seq = 0;
    unsigned long long sent_ms = 0;
    uint8_t reply[128];
    size_t reply_len = 0;
    int send_ret = 0;
    uint64_t now_ms = meshctl_now_ms();

    (void)user_data;

    if (!data || len < 20) {
        printf("[packet] received short packet: %zu bytes\n", len);
        return;
    }

    src_ip = ((uint32_t)data[12] << 24) |
             ((uint32_t)data[13] << 16) |
             ((uint32_t)data[14] << 8) |
             (uint32_t)data[15];
    dst_ip = ((uint32_t)data[16] << 24) |
             ((uint32_t)data[17] << 16) |
             ((uint32_t)data[18] << 8) |
             (uint32_t)data[19];

    format_ipv4_be(src_ip, src, sizeof(src));
    format_ipv4_be(dst_ip, dst, sizeof(dst));

    payload_len = len > 20 ? len - 20 : 0;
    if (payload_len >= sizeof(payload)) {
        payload_len = sizeof(payload) - 1;
    }

    if (payload_len > 0) {
        memcpy(payload, data + 20, payload_len);
    }
    payload[payload_len] = '\0';

    if (sscanf(payload, "%15[^:]:%u:%llu", kind, &seq, &sent_ms) == 3) {
        if (strcmp(kind, "meshctl-ping") == 0) {
            printf("[ping] request seq=%u %s -> %s\n", seq, src, dst);

            if (meshctl_build_ping_packet(g_config.virtual_ip, src, reply, sizeof(reply),
                                          &reply_len, 1, seq, (uint64_t)sent_ms) == 0) {
                send_ret = mesh_send_packet(g_mesh, reply, reply_len);
                if (send_ret == MESH_OK) {
                    printf("[ping] reply seq=%u %s -> %s\n", seq, g_config.virtual_ip, src);
                } else {
                    fprintf(stderr, "Failed to send ping reply: %s\n",
                            mesh_error_string((mesh_error_t)send_ret));
                }
            }
            return;
        }

        if (strcmp(kind, "meshctl-pong") == 0) {
            printf("[ping] reply seq=%u from %s rtt=%llums\n",
                   seq, src, (unsigned long long)(now_ms - (uint64_t)sent_ms));
            return;
        }
    }

    printf("[packet] proto=%u %s -> %s payload=\"%s\"\n", (unsigned)data[9], src, dst, payload);
}

#ifdef _WIN32
static BOOL WINAPI meshctl_console_handler(DWORD signal) {
    if (signal == CTRL_C_EVENT || signal == CTRL_BREAK_EVENT || signal == CTRL_CLOSE_EVENT) {
        g_running = 0;
        return TRUE;
    }
    return FALSE;
}
#else
static void meshctl_signal_handler(int sig) {
    (void)sig;
    g_running = 0;
}
#endif

static void meshctl_init_signals(void) {
#ifdef _WIN32
    SetConsoleCtrlHandler(meshctl_console_handler, TRUE);
#else
    signal(SIGINT, meshctl_signal_handler);
    signal(SIGTERM, meshctl_signal_handler);
#endif
}

static void meshctl_init_logger(void) {
    tlog_config_t log_config = {0};
    tlog_t *logger = NULL;
    turbo_console_sink_opts_t console_opts = {0};

    log_config.min_level = TURBO_LOG_LEVEL_INFO;
    logger = tlog_create(&log_config);
    if (!logger) {
        return;
    }

    console_opts.output = stdout;
    console_opts.use_colors = 1;
    console_opts.pattern = "[{time}] [{level}] {message}";
    tlog_add_sink(logger, turbo_sink_console_create(&console_opts));
    tlog_set_default(logger);
}

static int meshctl_run_doctor(const char *config_path) {
    meshctl_config_t cfg;

    meshctl_config_init(&cfg);
    if (meshctl_config_load(&cfg, config_path) != 0) {
        return 1;
    }

    if (meshctl_config_validate(&cfg) != 0) {
        return 1;
    }

    printf("Config check passed\n");
    meshctl_print_config(&cfg);
    return 0;
}

static int meshctl_run_genkey(void) {
    uint8_t secret_key[P2P_KEY_SIZE] = {0};
    uint8_t public_key[P2P_KEY_SIZE] = {0};
    char secret_key_hex[P2P_KEY_SIZE * 2 + 1] = {0};
    char public_key_hex[P2P_KEY_SIZE * 2 + 1] = {0};
    int ret = 0;

    ret = p2p_generate_private_key(secret_key);
    if (ret != P2P_OK) {
        fprintf(stderr, "Failed to generate identity private key\n");
        return 1;
    }

    ret = p2p_public_key_from_private_key(secret_key, public_key);
    if (ret != P2P_OK) {
        fprintf(stderr, "Failed to derive node id from identity private key\n");
        return 1;
    }

    meshctl_bytes_to_hex(secret_key, sizeof(secret_key), secret_key_hex, sizeof(secret_key_hex));
    meshctl_bytes_to_hex(public_key, sizeof(public_key), public_key_hex, sizeof(public_key_hex));

    printf("identity_secret_hex: %s\n", secret_key_hex);
    printf("node_id: %s\n", public_key_hex);
    printf("# keep identity_secret_hex private\n");
    return 0;
}

static int meshctl_run_init(int argc, char **argv) {
    meshctl_config_t cfg;
    uint8_t secret_key[P2P_KEY_SIZE] = {0};
    uint8_t public_key[P2P_KEY_SIZE] = {0};
    char secret_key_hex[P2P_KEY_SIZE * 2 + 1] = {0};
    char public_key_hex[P2P_KEY_SIZE * 2 + 1] = {0};
    const char *output_path = NULL;
    FILE *fp = NULL;
    int ret = 0;
    int i = 0;

    meshctl_config_init(&cfg);
    cfg.ice_enabled = 1;

    for (i = 0; i < argc; i++) {
        if ((strcmp(argv[i], "-o") == 0 || strcmp(argv[i], "--output") == 0) && i + 1 < argc) {
            output_path = argv[++i];
        } else if (strcmp(argv[i], "--node-name") == 0 && i + 1 < argc) {
            strncpy(cfg.node_name, argv[++i], sizeof(cfg.node_name) - 1);
        } else if (strcmp(argv[i], "--network-id") == 0 && i + 1 < argc) {
            strncpy(cfg.network_id, argv[++i], sizeof(cfg.network_id) - 1);
        } else if (strcmp(argv[i], "--virtual-ip") == 0 && i + 1 < argc) {
            strncpy(cfg.virtual_ip, argv[++i], sizeof(cfg.virtual_ip) - 1);
        } else if (strcmp(argv[i], "--advertise-ip") == 0 && i + 1 < argc) {
            strncpy(cfg.advertise_ip, argv[++i], sizeof(cfg.advertise_ip) - 1);
        } else if (strcmp(argv[i], "--virtual-prefix") == 0 && i + 1 < argc) {
            cfg.virtual_prefix = (unsigned int)strtoul(argv[++i], NULL, 10);
        } else if (strcmp(argv[i], "--listen-port") == 0 && i + 1 < argc) {
            cfg.listen_port = (int)strtol(argv[++i], NULL, 10);
        } else if (strcmp(argv[i], "--ice-enabled") == 0 && i + 1 < argc) {
            if (meshctl_parse_bool_arg(argv[++i], &cfg.ice_enabled) != 0) {
                fprintf(stderr, "Invalid value for --ice-enabled: expected true/false/1/0\n");
                return 1;
            }
        } else if (strcmp(argv[i], "--ice-allow-loopback") == 0 && i + 1 < argc) {
            if (meshctl_parse_bool_arg(argv[++i], &cfg.ice_allow_loopback) != 0) {
                fprintf(stderr, "Invalid value for --ice-allow-loopback: expected true/false/1/0\n");
                return 1;
            }
        } else if (strcmp(argv[i], "--bootstrap") == 0 && i + 1 < argc) {
            if (meshctl_config_add_bootstrap(&cfg, argv[++i]) != 0) {
                fprintf(stderr, "Too many bootstrap peers\n");
                return 1;
            }
        } else if (strcmp(argv[i], "--stun") == 0 && i + 1 < argc) {
            if (meshctl_config_add_stun(&cfg, argv[++i]) != 0) {
                fprintf(stderr, "Too many stun servers\n");
                return 1;
            }
        } else {
            fprintf(stderr, "Unknown init option: %s\n", argv[i]);
            return 1;
        }
    }

    if (!output_path) {
        fprintf(stderr, "init requires -o <mesh.yaml>\n");
        return 1;
    }

    if (meshctl_path_exists(output_path)) {
        fprintf(stderr, "Refusing to overwrite existing file: %s\n", output_path);
        return 1;
    }

    ret = p2p_generate_private_key(secret_key);
    if (ret != P2P_OK) {
        fprintf(stderr, "Failed to generate identity private key\n");
        return 1;
    }

    ret = p2p_public_key_from_private_key(secret_key, public_key);
    if (ret != P2P_OK) {
        fprintf(stderr, "Failed to derive node id from identity private key\n");
        return 1;
    }

    meshctl_bytes_to_hex(secret_key, sizeof(secret_key), secret_key_hex, sizeof(secret_key_hex));
    meshctl_bytes_to_hex(public_key, sizeof(public_key), public_key_hex, sizeof(public_key_hex));
    strncpy(cfg.identity_secret_hex, secret_key_hex, sizeof(cfg.identity_secret_hex) - 1);

    if (meshctl_config_validate(&cfg) != 0) {
        return 1;
    }

    fp = fopen(output_path, "wb");
    if (!fp) {
        fprintf(stderr, "Failed to open output file: %s\n", output_path);
        return 1;
    }

    if (meshctl_write_init_config(fp, &cfg, public_key_hex) != 0) {
        fclose(fp);
        fprintf(stderr, "Failed to write config file: %s\n", output_path);
        return 1;
    }

    fclose(fp);
    printf("Wrote starter config: %s\n", output_path);
    printf("node_id: %s\n", public_key_hex);
    return 0;
}

static int meshctl_run_up(const char *config_path) {
    mesh_config_t mesh_cfg;
    turbo_thread_t stdin_thread = NULL;
    char command[MESHCTL_MAX_COMMAND];
    int ret = 0;
    int ticks = 0;

    meshctl_config_init(&g_config);
    if (meshctl_config_load(&g_config, config_path) != 0) {
        return 1;
    }

    if (meshctl_config_validate(&g_config) != 0) {
        return 1;
    }

    meshctl_init_logger();
    meshctl_init_signals();
    meshctl_command_queue_init(&g_command_queue);

    mesh_config_init(&mesh_cfg);
    mesh_cfg.virtual_ip = g_config.virtual_ip;
    mesh_cfg.virtual_prefix = (uint8_t)g_config.virtual_prefix;
    mesh_cfg.listen_port = g_config.listen_port;
    mesh_cfg.advertise_ip = g_config.advertise_ip[0] ? g_config.advertise_ip : NULL;
    mesh_cfg.identity_secret_hex =
        g_config.identity_secret_hex[0] ? g_config.identity_secret_hex : NULL;
    mesh_cfg.network_id = g_config.network_id;
    mesh_cfg.enable_ice = g_config.ice_enabled;
    mesh_cfg.ice_stun_servers = g_config.stun_servers;
    mesh_cfg.ice_stun_count = g_config.stun_count;
    mesh_cfg.ice_allow_loopback = g_config.ice_allow_loopback;
    mesh_cfg.bootstrap_peers = g_config.bootstrap_peers;
    mesh_cfg.bootstrap_count = g_config.bootstrap_count;
    mesh_cfg.route_rules = g_config.route_rules;
    mesh_cfg.route_rule_count = g_config.route_rule_count;
    mesh_cfg.local_egress_cidrs = g_config.local_egress_cidrs;
    mesh_cfg.local_egress_count = g_config.local_egress_count;
    mesh_cfg.local_egress_allow_cidrs = g_config.local_egress_allow_cidrs;
    mesh_cfg.local_egress_allow_count = g_config.local_egress_allow_count;
    mesh_cfg.magic_dns_domain =
        g_config.magic_dns_domain[0] ? g_config.magic_dns_domain : NULL;
    mesh_cfg.magic_dns_records = g_config.magic_dns_records;
    mesh_cfg.magic_dns_record_count = g_config.magic_dns_record_count;
    mesh_cfg.packet_policy_rules = g_config.packet_policy_rules;
    mesh_cfg.packet_policy_rule_count = g_config.packet_policy_rule_count;
    mesh_cfg.peer_allow_cidrs = g_config.peer_allow_cidrs;
    mesh_cfg.peer_allow_count = g_config.peer_allow_count;
    mesh_cfg.peer_allow_node_ids = g_config.peer_allow_node_ids;
    mesh_cfg.peer_allow_node_id_count = g_config.peer_allow_node_id_count;
    mesh_cfg.peer_protocol_major = g_config.peer_protocol_major;
    mesh_cfg.on_peer_connected = on_peer_connected;
    mesh_cfg.on_peer_disconnected = on_peer_disconnected;
    mesh_cfg.on_packet_received = on_packet_received;

    g_mesh = mesh_create(&mesh_cfg);
    if (!g_mesh) {
        fprintf(stderr, "Failed to create mesh\n");
        meshctl_command_queue_destroy(&g_command_queue);
        return 1;
    }

    printf("Starting node '%s'\n", g_config.node_name);
    meshctl_print_config(&g_config);

    ret = mesh_start(g_mesh);
    if (ret != MESH_OK) {
        fprintf(stderr, "Failed to start mesh: %s\n", mesh_error_string((mesh_error_t)ret));
        mesh_destroy(g_mesh);
        g_mesh = NULL;
        meshctl_command_queue_destroy(&g_command_queue);
        return 1;
    }

    turbo_thread_create(&stdin_thread, meshctl_stdin_thread, &g_command_queue);

    printf("Mesh is running. Type 'help' for commands.\n");

    while (g_running || meshctl_command_queue_has_pending(&g_command_queue)) {
        mesh_poll(g_mesh, 100);

        while (meshctl_command_queue_pop(&g_command_queue, command, sizeof(command))) {
            meshctl_handle_command(g_mesh, command);
        }

        ticks++;
        if (ticks >= 50) {
            ticks = 0;
            meshctl_print_status(g_mesh);
        }

#ifdef _WIN32
        Sleep(100);
#else
        usleep(100000);
#endif
    }

    meshctl_command_queue_stop(&g_command_queue);
    turbo_thread_destroy(&stdin_thread);
    mesh_stop(g_mesh);
    mesh_destroy(g_mesh);
    g_mesh = NULL;
    meshctl_command_queue_destroy(&g_command_queue);
    return 0;
}

static void meshctl_print_usage(const char *argv0) {
    printf("Usage:\n");
    printf("  %s genkey\n", argv0);
    printf("  %s init -o <mesh.yaml> [--node-name <name>] [--network-id <id>]\n", argv0);
    printf("         [--virtual-ip <ip>] [--virtual-prefix <n>] [--listen-port <port>]\n");
    printf("         [--advertise-ip <ip>] [--bootstrap <ip:port>] [--stun <stun:host:port>]\n");
    printf("         [--ice-enabled <true|false>] [--ice-allow-loopback <true|false>]\n");
    printf("  %s doctor -c <mesh.yaml>\n", argv0);
    printf("  %s up -c <mesh.yaml>\n", argv0);
}

int main(int argc, char **argv) {
    const char *command = NULL;
    const char *config_path = NULL;
    int i = 0;

    if (argc < 2) {
        meshctl_print_usage(argv[0]);
        return 1;
    }

    command = argv[1];
    if (strcmp(command, "genkey") == 0) {
        return meshctl_run_genkey();
    }

    if (strcmp(command, "init") == 0) {
        return meshctl_run_init(argc - 2, argv + 2);
    }

    for (i = 2; i < argc; i++) {
        if ((strcmp(argv[i], "-c") == 0 || strcmp(argv[i], "--config") == 0) && i + 1 < argc) {
            config_path = argv[i + 1];
            i++;
        }
    }

    if (!config_path) {
        meshctl_print_usage(argv[0]);
        return 1;
    }

    if (strcmp(command, "doctor") == 0) {
        return meshctl_run_doctor(config_path);
    }

    if (strcmp(command, "up") == 0) {
        return meshctl_run_up(config_path);
    }

    meshctl_print_usage(argv[0]);
    return 1;
}
